kernel: Add override to COMPATIBLE_MACHINE
LIN10-2540

Add machine override to COMPATIBLE_MACHINE to avoid overwriting the
value set by other layers when building with "--all-layers", which
may cause the following build error.

"linux-yocto-ovp-guest PROVIDES virtual/kernel but was skipped:
incompatible with host aarch64-wrs-linux (not in COMPATIBLE_HOST)
linux-yocto-rt PROVIDES virtual/kernel but was skipped: Recipe is
blacklisted: Only linux-yocto 4.12 is supported,
version 4.9.49+gitAUTOINC+6acae6f720_0817a7b3a8 skipped. Set
PREFERRED_VERSION_linux-yocto = "4.12.%"
ERROR: Required build target 'wrlinux-image-glibc-std' has no
buildable providers.
Missing or unbuildable dependency chain was:
['wrlinux-image-glibc-std', 'virtual/kernel']"

Signed-off-by: He Zhe <zhe.he@windriver.com>